-- ─────────────────────────────────────────────────────────────────────────────
-- Bulk import v2 — role-aware
--
-- 1. Add 'supervisor' to user_role enum.
--    To add more roles in future: ALTER TYPE user_role ADD VALUE 'new_role';
-- 2. Drop old bulk_import_member (signature changed).
-- 3. Re-create bulk_import_user — accepts any role:
--    - member  → creates users row + members row + follow-up tasks generated by app
--    - coach / supervisor / jco / nco → creates users row only
-- ─────────────────────────────────────────────────────────────────────────────

-- ── 1. New role ───────────────────────────────────────────────────────────────
-- To add more roles later, run: ALTER TYPE user_role ADD VALUE 'your_new_role';
alter type user_role add value if not exists 'supervisor';

-- ── 2. Drop old function (param signature changed) ────────────────────────────
drop function if exists bulk_import_member(text, uuid, text, text, membership_type, date, numeric, numeric);

-- ── 3. bulk_import_user() — role-aware ───────────────────────────────────────
create or replace function bulk_import_user(
  p_name         text,
  p_upline_id    uuid,                            -- required: upline/coach id
  p_role         user_role       default 'member',
  p_phone        text            default null,
  p_email        text            default null,
  p_membership   membership_type default 'basic', -- used only when role = member
  p_join_date    date            default current_date,
  p_ideal_weight numeric         default null,    -- used only when role = member
  p_cur_weight   numeric         default null     -- used only when role = member
) returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id uuid;
begin
  -- Only club owner can bulk-import.
  if app_user_role() <> 'club_owner' then
    raise exception 'Only the club owner can bulk-import users';
  end if;

  -- Upline must exist and be active.
  if not exists (
    select 1 from users
    where id = p_upline_id
      and status = 'active'
  ) then
    raise exception 'Upline not found or not active: %', p_upline_id;
  end if;

  -- club_owner role cannot be bulk-imported (security).
  if p_role = 'club_owner' then
    raise exception 'Cannot bulk-import club_owner role';
  end if;

  -- Prevent duplicate phone.
  if p_phone is not null and btrim(p_phone) <> '' and exists (
    select 1 from users where phone = btrim(p_phone)
  ) then
    raise exception 'Phone already registered: %', p_phone;
  end if;

  -- Prevent duplicate email.
  if p_email is not null and btrim(p_email) <> '' and exists (
    select 1 from users where email = lower(btrim(p_email))
  ) then
    raise exception 'Email already registered: %', p_email;
  end if;

  -- Insert users row (active, no auth link — they set password via invite later).
  insert into users (name, phone, email, role, parent_id, status)
  values (
    btrim(p_name),
    nullif(btrim(coalesce(p_phone, '')), ''),
    nullif(lower(btrim(coalesce(p_email, ''))), ''),
    p_role,
    p_upline_id,
    'active'
  )
  returning id into v_id;

  -- Insert members row for member + supervisor (both on the health track).
  if p_role in ('member', 'supervisor') then
    insert into members (
      user_id, coach_id, membership_type, join_date,
      ideal_weight, current_weight
    )
    values (
      v_id,
      p_upline_id,
      p_membership,
      p_join_date,
      p_ideal_weight,
      p_cur_weight
    );
  end if;

  return v_id;
end;
$$;

grant execute on function bulk_import_user(
  text, uuid, user_role, text, text, membership_type, date, numeric, numeric
) to authenticated;
